### ISSUE TITLE
Does not work on Raspberry Pi

### ISSUE THREAD

**Issue by MDSilber** [theycallmeswift/BreakfastSerial#3]
This is the script I'm using to test BreakfastSerial
###### 

from BreakfastSerial import Arduino, Servo

from time import sleep

board = Arduino()
servo = Servo(board, 10)

import code
code.InteractiveConsole(locals=globals()).interact()
###### 

When running this on an Ubuntu Virtual Machine, it works fine. When running this with Raspberry Pi, this consistently happens:

First run (tries to connect to ttyACM0): 
python servo_test.py
Connecting to /dev/ttyACM0
Python 2.7.3 (default, Jan 13 2013, 11:20:46)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)

> > > Exception in thread Thread-1:
> > > Traceback (most recent call last):
> > >   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
> > >     self.run()
> > >   File "/usr/local/lib/python2.7/dist-packages/BreakfastSerial/BreakfastSerial.py", line 80, in run
> > >     while self.board.bytes_available():
> > >   File "/usr/local/lib/python2.7/dist-packages/pyfirmata/pyfirmata.py", line 225, in bytes_available
> > >     return self.sp.inWaiting()
> > >   File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 435, in inWaiting
> > >     s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
> > > IOError: [Errno 5] Input/output error
> > > 
> > > exit()

Second run (Tries to connect to ttyACM1):
python servo_test.py
Connecting to /dev/ttyACM1
Python 2.7.3 (default, Jan 13 2013, 11:20:46)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)

> > > servo.center() #This call worked properly before the exception below
> > > Exception in thread Thread-1:
> > > Traceback (most recent call last):
> > >   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
> > >     self.run()
> > >   File "/usr/local/lib/python2.7/dist-packages/BreakfastSerial/BreakfastSerial.py", line 80, in run
> > >     while self.board.bytes_available():
> > >   File "/usr/local/lib/python2.7/dist-packages/pyfirmata/pyfirmata.py", line 225, in bytes_available
> > >     return self.sp.inWaiting()
> > >   File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 435, in inWaiting
> > >     s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
> > > IOError: [Errno 5] Input/output error
> > > exit()

Every subsequent run(tries connecting to ttyACM0)
python servo_test.py
Connecting to /dev/ttyACM0
Traceback (most recent call last):
  File "servo_test.py", line 5, in <module>
    board = Arduino()
  File "/usr/local/lib/python2.7/dist-packages/BreakfastSerial/BreakfastSerial.py", line 31, in **init**
    raise FirmataNotOnBoardException
BreakfastSerial.BreakfastSerial.FirmataNotOnBoardException

**Comment by theycallmeswift** [comment]
If you fire up the arduino IDE, what serial port is the actual board on?

**Comment by MDSilber** [comment]
Haven't tried anything with the Arduino GUI on the Raspberry Pi. I loaded Firmata onto it from my other computer, then connected it to the Raspberry Pi. Could that make a difference?

**Comment by theycallmeswift** [comment]
Not sure to be honest. It's worth a shot. Knowing what serial port the board is actually on is the important bit.

**Comment by MDSilber** [comment]
It prints out ttyACM0 or ttyACM1 when I make the Arduino() call, if that's any indication.

**Comment by theycallmeswift** [comment]
Yeah, but that doesn't help me know what port it's actually on. Do this:
1. Put the arduino IDE on your Pi
2. Upload firmata and note which serial port the board is on
3. Test it to see if that solves the problem. 
4. Report back here what the result was and the correct port. 
   —

**Comment by MDSilber** [comment]
When I try o load StandardFirmata onto the arduino from the raspberry pi, it looks like it's on COM1, but it doesn't even compile. This is what I get:
/home/pi/arduino-1.0/hardware/arduino/cores/arduino/Print.cpp: In member function ‘size_t Print::print(const __FlashStringHelper*)’:
/home/pi/arduino-1.0/hardware/arduino/cores/arduino/Print.cpp:44:9: error: ‘prog_char’ does not name a type
/home/pi/arduino-1.0/hardware/arduino/cores/arduino/Print.cpp:47:23: error: ‘p’ was not declared in this scope

**Comment by theycallmeswift** [comment]
`COM1` is definitely wrong.  How did you install the IDE?  I would do the following:

```
$ sudo apt-get update
$ sudo apt-get install arduino
```

and then run these:

```
$ sudo usermod -a -G tty pi
$ sudo usermod -a -G dialout pi
```

I'm pretty sure you're looking for something like 'ttyUSB0'.  Also, in case it matters, what linux distro is on your PI?

**Comment by MDSilber** [comment]
I get ttyACM0 generally. Generally the first time I run it, it works fine, but on the next run, it throws the FirmataNotOnBoardException. Loaded StandardFirmata onto the arduino from the raspberry pi though (got that working).

There was no output when I ran those commands

**Comment by MDSilber** [comment]
Loaded StandardFirmata onto the arduino from the raspberry pi, and then tried running the following script:

from BreakfastSerial import Arduino, Led, Servo

board = Arduino()
led = Led(board, 13)
servo = Servo(board, 10)

This is the output I get:
Connecting to /dev/ttyACM0
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/BreakfastSerial/BreakfastSerial.py", line 80, in run
  File "/usr/local/lib/python2.7/dist-packages/pyfirmata/pyfirmata.py", line 225, in bytes_available
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 435, in inWaiting
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'ioctl'

**Comment by theycallmeswift** [comment]
Hmm... this is pretty strange.  Let's start isolating things.  If you change:

```
board = Arduino()
```

to:

```
board = Arduino("/dev/ttyACM0")
```

Does it ever throw the FirmataNotOnBoard exception?

---

It might also have something to do with the serial port login settings.  Can you share the output of `/etc/inittab`?

And, as a last resort, you mind walking through [this node.js tutorial](http://niltoid.com/blog/raspberry-pi-arduino/)?  Let's see if we can isolate wether or not it's a problem with BreakfastSerial or the Pi.

FYI, I'm traveling right now (in Brazil).  I don't have a raspberry Pi with me to help debug.  Will be back on the 6th, it's on my todo list for that day.

**Comment by Daniel-Vacha** [comment]
Hi 
I had same problem. It seems strange but you probably connect servo to Arduino  without special power source for Arduino you power Arduino from Pi same as me. Try to  connect supplemental source only for servo. 
I hope it helps you, at least this solution helped myself.
Kind regards Daniel

**Comment by MDSilber** [comment]
Closing since this hasn't gotten attention in 2.5 years. If someone wants to reopen feel freel
